CONFIGS_DIRECTORY = "configs/"
DATA_DIRECTORY = "data/"
EXPORT_DIRECTORY = "export/"
TOOLTIP_PATH = "mappings/tags.da"
ATTRIBUTES_PATH = "mappings/attributes.da"

GENERAL_CONFIG_FILE = "config.json"
LOG_DIRECTORY = "logs"
MANUFACTURER_ENDING = ".lugg"
MANUFACTURER_INFO_ENDING = ".ilugg"
PRODUCT_ENDING = ".prod"
PRODUCT_TYPE_ID = "0000191"
ARCHIVE_DIRECTORY = "Archiv"

CONFIGURATOR_NAME = "Konfigurator"
SHOP_NAME = "Shop"
PRICE_NAME = "Listenpreise"
COMPLETE_NAME = "Komplett"
