CONFIGS_DIRECTORY = "configs/"
DATA_DIRECTORY = "data/"
EXPORT_DIRECTORY = "export/"
TOOLTIP_PATH = "mappings/tags.da"
ATTRIBUTES_PATH = "mappings/MasterRecordMask.da"

KEEP_LOGS = 2

GENERAL_CONFIG_FILE = "config.json"
FORMATTING_CONFIG_FILE = "Formatierungen.yaml"
LOG_DIRECTORY = "logs"
MANUFACTURER_ENDING = ".lugg"
MANUFACTURER_INFO_ENDING = ".ilugg"
PRODUCT_ENDING = ".prod"
ARCHIVE_DIRECTORY = "Archiv"

TECHDATA = "TECHDATA"
PRODUCT_TYPE_ID = "0000191"
ARTICLE_NUMBER = "ARTNR"
WIDTH = "0000058"
DEPTH = "0000060"
HEIGHT = "0000059"

CONFIGURATOR_NAME = "Konfigurator"
GAMBIO_NAME = "Gambio"
SHOP_NAME = "Shop"
PRICE_NAME = "Listenpreise"
COMPLETE_NAME = "Komplett"
CUSTOM_NAME = "Custom"
